### PR TITLE
Close #40

### LINKED ISSUE #40: cg_iRIC_Read_Grid2d_Str_Size etc. returns invalid data when 3d grid exists.
The following functions does not work correctly when 3d grid exists. These functions should refer to the zone that stores 2d grid, but it actually refers to the zone that stores 3d grid currently.

* cg_iRIC_Read_Grid2d_Str_Size
* cg_iRIC_Read_Grid2d_Coords
* cg_iRIC_Read_Grid2d_Open
* cg_iRIC_Read_Sol_Grid2d_Open
* cg_iRIC_Read_Sol_Grid2d_Coords
* cg_iRIC_Write_Sol_Grid2d_Coords

### PR DESCRIPTION
**Pull request by kskinoue0612**
cg_iRIC_Read_Grid2d_Str_Size etc. returns invalid data when 3d grid exists.

### CODE REVIEW

**Comment by kskinoue0612** [comment]
Hi Scott,

This is the pull request to fix the issue that you've reported with FaSTMECH source code.
Can you make sure that after merging the pull request, cg_iRIC_Read_Grid2d_Str_Size etc. returns valid data in case 3D grid exists?

Thank you,

Keisuke Inoue

**Comment by scharlton2** [comment]
Hi Keisuke,

It fixes the unit test (unittests_cgnsfile):
case_GridRead_FaSTMECH_3d_results

but now it fails the unit tests (unittests_cgnsfile):
case_SolWriteStd_hdf5
case_SolWriteDivide_hdf5

Also, the fortran unit test (test1) is now failing in the develop_v4 branch.
It looks like it was broken by commit 257d28d.  It causes an hdf5 error 
when calling cg_iRIC_Write_ErrorCode.  It works in commit 07bd0f8.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your information. I'll check it.

Thanks,

Keisuke Inoue

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed a commit so that the following issue is fixed:

> but now it fails the unit tests (unittests_cgnsfile):
> case_SolWriteStd_hdf5
> case_SolWriteDivide_hdf5

> Also, the fortran unit test (test1) is now failing in the develop_v4 branch.
> It looks like it was broken by commit https://github.com/i-RIC/iriclib_v4/commit/257d28d754a129a8bd8768592fc6ed79e80f9911. It causes an hdf5 error
> when calling cg_iRIC_Write_ErrorCode. It works in commit https://github.com/i-RIC/iriclib_v4/commit/07bd0f8e5ee2a1682d9d54b842a71445fc3eb23a.

I tried to reproduce the issue with this branch.
I compiled iric.f90 to generate iric.mod, and then compiled test1.f90.

It outputs the following error log:

```
test1.f90(204): warning #5117: Bad # preprocessor line
#if 0
-^
test1.f90(266): warning #5117: Bad # preprocessor line
#endif
-^
test1.f90(208): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [CONDINDICES]
                        condindices(condid:condid, 1:2, 1:condindexlen(condid)), ier)
------------------------^
test1.f90(219): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [FUNC_PARAM]
                        func_param(condid:condid, 1:func_size(condid)), &
------------------------^
test1.f90(220): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [FUNC_VALUE]
                        func_value(condid:condid, 1:func_size(condid)), ier)
------------------------^
test1.f90(223): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [FUNC_REAL_PARAM]
                        func_real_param(condid:condid, 1:func_size(condid)),  &
------------------------^
test1.f90(224): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [FUNC_REAL_VALUE]
                        func_real_value(condid:condid, 1:func_size(condid)), ier)
------------------------^
test1.f90(227): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [FUNC_WITHNAME_PARAM]
                        func_withname_param(condid:condid, 1:func_size(condid)), ier)
------------------------^
test1.f90(230): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [FUNC_WITHNAME_VALUE]
                        func_withname_value(condid:condid, 1:func_size(condid)), ier)
------------------------^
compilation aborted for test1.f90 (code 1)
```

It looks that the result is different. Can you make sure you can build and link test1.F90 with the newest iric.f90?

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

If you use cmake to build and test iriclib it automatically turns on the fortran preprocessor.  You can turn it on manually using the following:

image

I checked your latest issue-40 branch and it's still throwing an hdf5 error here:

image

```
HDF5-DIAG: Error detected in HDF5 (1.8.21) thread 0:
  #000: D:\a\iricdev-2019\iricdev-2019\lib\src\CMake-hdf5-1.8.21\hdf5-1.8.21\src\H5G.c line 312 in H5Gcreate2(): unable to create group
    major: Symbol table
    minor: Unable to initialize object
  #001: D:\a\iricdev-2019\iricdev-2019\lib\src\CMake-hdf5-1.8.21\hdf5-1.8.21\src\H5Gint.c line 192 in H5G__create_named(): unable to create and link to group
    major: Symbol table
    minor: Unable to initialize object
  #002: D:\a\iricdev-2019\iricdev-2019\lib\src\CMake-hdf5-1.8.21\hdf5-1.8.21\src\H5L.c line 1636 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: D:\a\iricdev-2019\iricdev-2019\lib\src\CMake-hdf5-1.8.21\hdf5-1.8.21\src\H5L.c line 1880 in H5L_create_real(): can't insert link
    major: Symbol table
    minor: Unable to insert object
  #004: D:\a\iricdev-2019\iricdev-2019\lib\src\CMake-hdf5-1.8.21\hdf5-1.8.21\src\H5Gtraverse.c line 859 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: D:\a\iricdev-2019\iricdev-2019\lib\src\CMake-hdf5-1.8.21\hdf5-1.8.21\src\H5Gtraverse.c line 639 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: D:\a\iricdev-2019\iricdev-2019\lib\src\CMake-hdf5-1.8.21\hdf5-1.8.21\src\H5L.c line 1672 in H5L_link_cb(): name already exists
    major: Symbol table
    minor: Object already exists
```

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

thank you for your information to reproduce the issue. I’ll check and fix it.
I have a task to finish this week, so I think I’ll work on it next week. In my understanding, the issue does not affect your work to migrate FaSTMECH to v4. Am I right?

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

I don't think it affects Fastmech v4 migration.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

I've pushed another commit so that building test1.f90 succeeds.

Honestly speaking, I did not succeed to reproduce the situation that you've reported. I think I'm not familiar enough to CMake.
I've built test1.f90 manually using Intel OneAPI fortran compiler. With older iric.f90, compiling test1.f90 failed, and with new iric.f90, it succeeds. I've also made sure that test1.exe runs successfully.

Can you make sure if test1.f90 can be built successfully, and run without errors, please?

If not, maybe we can investigate what's happening in the next web meeting, by sharing our screens.

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Today is a holiday in the US.  I will try to test it tomorrow.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your response. No problem. Thank you for reviewing.

Thanks,

Keisuke

2022年6月21日(火) 8:21 Charlton, Scott R. ***@***.***>:

**Comment by scharlton2** [comment]
Hi Keisuke,

I realized what was going on.  The hdf5 file for test1 succeeds when it's first run but fails on all successive runs.  I modified test1 to always use a fresh copy to avoid this.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you, I’ve got it!

Thanks,

Keisuke

2022年6月22日(水) 4:38 Charlton, Scott R. ***@***.***>:
